--<ScriptOptions statementTerminator=";"/>

DROP VIEW "VSTRIKERDB"."VW_ACCOUNT_DETAIL";

CREATE VIEW "VSTRIKERDB"."VW_ACCOUNT_DETAIL" (NAME, ACCOUNT_LOCATION, VALIDATED, LAST_VALIDATION_DATE, API_ID, ACCOUNT_ID, API_TYPE_ID, URL, SECRET_KEY, BUCKET, SUBTENANT, HTTP_ADDRESS_IP, HTTPS_ADDRESS_IP, HTTP_ADDRESS_PORT, HTTPS_ADDRESS_PORT, API_TYPE_NAME, API_TYPE_URL, API_TYPE_DESCRIPTION) 
WITH CASCADED CHECK OPTION;

