--<ScriptOptions statementTerminator=";"/>

ALTER TABLE OBJECT_SIZE_REPORT_UNIT DROP CONSTRAINT FK_OBJECT_SIZE_REPORT_UNIT_CONFIGURATION_TEMPLATE;

ALTER TABLE API_TYPE DROP CONSTRAINT FK_API_TYPE_CRUD_OPERATION_TYPE;

ALTER TABLE CONFIGURATION_TEMPLATE DROP CONSTRAINT CONSTRAINT_1;

ALTER TABLE TEST_CONFIGURATION DROP CONSTRAINT CONSTRAINT_D;

ALTER TABLE CONFIGURATION_TEMPLATE DROP CONSTRAINT PK_CONFIGURATION_TEMPLATE_INDEX_1;

ALTER TABLE API DROP CONSTRAINT CONSTRAINT_F;

ALTER TABLE CRUD_OPERATION_TYPE DROP CONSTRAINT CONSTRAINT_4;

ALTER TABLE EXECUTION_PLAN DROP CONSTRAINT CONSTRAINT_2;

ALTER TABLE EXECUTION_REPORT_DATA DROP CONSTRAINT CONSTRAINT_FF;

ALTER TABLE EXECUTION_REPORT DROP CONSTRAINT CONSTRAINT_A;

ALTER TABLE TEST_PLAN_OPERATION DROP CONSTRAINT CONSTRAINT_61;

ALTER TABLE CRUD_OPERATION_TYPE DROP CONSTRAINT PK_CRUD_OPERATION_TYPE_0_INDEX_4;

ALTER TABLE OBJECT_SIZE_REPORT_UNIT DROP CONSTRAINT CONSTRAINT_AA;

ALTER TABLE API_TYPE DROP CONSTRAINT CONSTRAINT_6;

ALTER TABLE ACCOUNT DROP CONSTRAINT CONSTRAINT_E;

ALTER TABLE API_SELECTED DROP CONSTRAINT CONSTRAINT_9;

DROP INDEX PRIMARY_KEY_61;

DROP INDEX PK_TEST_PLAN_OPERATION_0_INDEX_6;

DROP INDEX PK_API_SELECTED_INDEX_9;

DROP INDEX PK_EXECUTIONPLAN_1_INDEX_2;

DROP INDEX PRIMARY_KEY_F;

DROP INDEX PK_CRUD_OPERATION_TYPE_0_INDEX_4;

DROP INDEX PRIMARY_KEY_FF;

DROP INDEX PRIMARY_KEY_2;

DROP INDEX PRIMARY_KEY_4;

DROP INDEX PK_API_0_INDEX_F;

DROP INDEX PK_TEST_CONFIGURATION_INDEX_D;

DROP INDEX PRIMARY_KEY_E;

DROP INDEX PK_API_SELECTED_0_INDEX_9;

DROP INDEX PRIMARY_KEY_A;

DROP INDEX PRIMARY_KEY_D;

DROP INDEX PK_EXECUTION_REPORT_DATA_INDEX_F;

DROP INDEX PRIMARY_KEY_9;

DROP INDEX PK_API_1_INDEX_F;

DROP INDEX PRIMARY_KEY_6;

DROP INDEX PK_EXECUTIONPLAN_0_INDEX_2;

DROP INDEX PK_EXECUTIONPLAN_2_INDEX_2;

DROP INDEX PK_EXECUTION_PLAN_INDEX_2;

DROP INDEX PRIMARY_KEY_AA;

DROP INDEX PK_CONFIGURATION_TEMPLATE_INDEX_1;

DROP INDEX PK_TEST_PLAN_OPERATION_1_INDEX_6;

DROP INDEX PRIMARY_KEY_1;

DROP TABLE CRUD_OPERATION_TYPE;

DROP TABLE ACCOUNT;

DROP TABLE EXECUTION_REPORT_DATA;

DROP TABLE API_TYPE;

DROP TABLE CONFIGURATION_TEMPLATE;

DROP TABLE API;

DROP TABLE TEST_PLAN_OPERATION;

DROP TABLE EXECUTION_PLAN;

DROP TABLE OBJECT_SIZE_REPORT_UNIT;

DROP TABLE EXECUTION_REPORT;

DROP TABLE TEST_CONFIGURATION;

DROP TABLE API_SELECTED;

CREATE TABLE CRUD_OPERATION_TYPE (
		CRUD_OPERATION_TYPE_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_2BAA3876_91EB_40E6_BEBC_DE827A6A6599) NOT NULL,
		API_TYPE_ID INTEGER NOT NULL,
		CRUD_OPERATION_NAME VARCHAR(100),
		CRUD OPERATION VALUE VARCHAR(1000)
	);

CREATE TABLE ACCOUNT (
		ACCOUNT_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_EE5B1159_D068_4DE1_8701_80D1263EEA39) NOT NULL,
		NAME VARCHAR(100) NOT NULL,
		ACCOUNT_LOCATION VARCHAR(255) NOT NULL,
		VALIDATED BOOLEAN DEFAULT 'False' NOT NULL,
		LAST_VALIDATION_DATE DATE
	);

CREATE TABLE EXECUTION_REPORT_DATA (
		EXECUTION_REPORT_DATA_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_75BDAD66_530F_4093_91C9_4459E88A5671) NOT NULL,
		EXECUTION_REPORT_ID INTEGER NOT NULL,
		DATA_KEY VARCHAR(255) NOT NULL,
		DATA_VALUE VARCHAR(500) NOT NULL
	);

CREATE TABLE API_TYPE (
		API_TYPE_ID INTEGER DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_2BCD59B7_F641_469A_B2A9_BAF424629625) NOT NULL,
		API_TYPE_NAME VARCHAR(100) NOT NULL,
		API_TYPE_URL VARCHAR(255),
		API_TYPE_DESCRIPTION VARCHAR(255)
	);

CREATE TABLE CONFIGURATION_TEMPLATE (
		CONFIGURATION_TEMPLATE_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_46EBE51D_80A5_45AF_B4CA_B9848B239212) NOT NULL,
		CONF_TEMP_OBJECT_SIZE_REPORT_UNIT_ID INTEGER NOT NULL,
		CONF_TEMP_NAME VARCHAR(255) NOT NULL,
		CONF_TEMP_DESCRIPTION VARCHAR(255),
		CONF_TEMP_OBJECT_SIZE INTEGER,
		CONF_TEMP_NUMBER_OF_OPERATIONS INTEGER NOT NULL,
		CONF_TEMP_NUMBER_OF_THREADS INTEGER DEFAULT 1 NOT NULL,
		CONF_TEMP_CREATE_OPERATION BOOLEAN,
		CONF_TEMP_READ_OPERATION BOOLEAN,
		CONF_TEMP_UPDATE_OPERATION BOOLEAN,
		CONF_TEMP_DELETE_OPERATION BOOLEAN,
		CONF_TEMP_CREATE_PERCENT INTEGER,
		CONF_TEMP_READ_PERCENT INTEGER,
		CONF_TEMP_UPDATE_PERCENT INTEGER,
		CONF_TEMP_DELETE_PERCENT INTEGER,
		CONF_TEMP_NUMBER_OF_RETRY INTEGER,
		CONF_TEMP_ENABLE_RAND_SIZE_OBJECT BOOLEAN,
		CONF_TEMP_MIN_RAND_SIZE_OBJECT INTEGER,
		CONF_TEMP_MAX_RAND_SIZE_OBJECT INTEGER,
		CONF_TEMP_CREATED_DATE DATE DEFAULT CURRENT_DATE(),
		CONF_TEMP_SMALL_SIZE_PERCENT INTEGER,
		CONF_TEMP_MEDIUM_SIZE_PERCENT INTEGER,
		CONF_TEMP_LARGE_SIZE_PERCENT INTEGER
	);

CREATE TABLE API (
		API_ID INTEGER DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_81E817BD_6540_4F85_A043_F52E06FC353D) NOT NULL,
		ACCOUNT_ID INTEGER NOT NULL,
		API_TYPE_ID INTEGER NOT NULL,
		URL VARCHAR(255) NOT NULL,
		SECRET_KEY VARCHAR(255) NOT NULL,
		BUCKET VARCHAR(255),
		SUBTENANT VARCHAR(255),
		HTTP_ADDRESS_IP VARCHAR(16) NOT NULL,
		HTTPS_ADDRESS_IP VARCHAR(16),
		HTTP_ADDRESS_PORT VARCHAR(5) NOT NULL,
		HTTPS_ADDRESS_PORT VARCHAR(5)
	);

CREATE TABLE TEST_PLAN_OPERATION (
		TEST_PLAN_OPERATION_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_7AE70DBC_C303_4634_86A2_71FC7603EA71) NOT NULL,
		API_TYPE_ID INTEGER NOT NULL,
		CRUD_OPERATION_TYPE_ID INTEGER NOT NULL,
		CRUD_OPERATION INTEGER NOT NULL,
		FILE_URL VARCHAR(255)
	);

CREATE TABLE EXECUTION_PLAN (
		EXECUTION_PLAN_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_F6677361_BC04_47ED_BEFC_84D59089549B) NOT NULL,
		ACCOUNT_ID INTEGER NOT NULL,
		CONFIGURATION_TEMPLATE_ID INTEGER,
		TESTCONFIGURATION_ID INTEGER,
		EXECUTION_REPORT_ID INTEGER NOT NULL
	);

CREATE TABLE OBJECT_SIZE_REPORT_UNIT (
		OBJECT_SIZE_REPORT_UNIT_ID INTEGER DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_56043894_BB6F_4039_A4F2_583512322C86) NOT NULL,
		REPORT_UNIT_NAME VARCHAR(100) NOT NULL,
		REPORT_UNIT_VALUE VARCHAR(100)
	);

CREATE TABLE EXECUTION_REPORT (
		EXECUTION_REPORT_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_289A2453_CCFA_4DD1_8CF3_71B41BF29AFE) NOT NULL,
		EXECUTION_NAME VARCHAR(255) NOT NULL,
		EXECUTION_DATE DATE,
		TOTAL_THROUGHPUT VARCHAR(100),
		MAX_THROUGHPUT VARCHAR(100),
		MIN_THROUGHPUT VARCHAR(100),
		TOTAL_VOLUME_SENT VARCHAR(100),
		TOTAL_VOLUME_RECEIVED VARCHAR(100),
		AVG_LATENCY_PER_CRUD_OPERATION VARCHAR(100),
		NUMBER_REQUEST_SEC INTEGER,
		PERECENT_FAILED_REQUEST INTEGER
	);

CREATE TABLE TEST_CONFIGURATION (
		TESTCONFIGURATION_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_E3578308_073D_4D35_97FD_299F7663644C) NOT NULL,
		OBJECT_SIZE_REPORT_UNIT_ID INTEGER NOT NULL,
		TEST_CONFIG_NAME VARCHAR(255) NOT NULL,
		TEST_CONFIG_DESCRIPTION VARCHAR(255),
		OBJECT_SIZE INTEGER,
		NUMBER_OF_OPERATIONS INTEGER NOT NULL,
		NUMBER_OF_THREADS INTEGER DEFAULT 1 NOT NULL,
		CREATE_OPERATION BOOLEAN,
		READ_OPERATION BOOLEAN,
		UPDATE_OPERATION BOOLEAN,
		DELETE_OPERATION BOOLEAN,
		CREATE_PERCENT INTEGER,
		READ_PERCENT INTEGER,
		UPDATE_PERCENT INTEGER,
		DELETE_PERCENT INTEGER,
		NUMBER_OF_RETRY INTEGER,
		ENABLE_RAND_SIZE_OBJECT BOOLEAN,
		MIN_RAND_SIZE_OBJECT INTEGER,
		MAX_RAN_DSIZE_OBJECT INTEGER,
		CREATED_DATE DATE DEFAULT CURRENT_DATE(),
		SMALL_SIZE_PERCENT INTEGER,
		MEDIUM_SIZE_PERCENT INTEGER,
		LARGE_SIZE_PERCENT INTEGER,
		API_SELCTED_ID INTEGER NOT NULL
	);

CREATE TABLE API_SELECTED (
		API_SELECTED_ID BIGINT DEFAULT (NEXT VALUE FOR VSTRIKERDB.SYSTEM_SEQUENCE_1B8F14A2_F1CE_4A52_AA15_411D580DFF98) NOT NULL,
		TESTCONFIGURATION_ID INTEGER NOT NULL,
		API_TYPE_ID INTEGER NOT NULL,
		API_SELECTED_HTTP BOOLEAN,
		API_SELECTED_HTTPS BOOLEAN
	);

CREATE UNIQUE INDEX PRIMARY_KEY_61 ON TEST_PLAN_OPERATION (TEST_PLAN_OPERATION_ID ASC);

CREATE UNIQUE INDEX PK_TEST_PLAN_OPERATION_0_INDEX_6 ON TEST_PLAN_OPERATION (API_TYPE_ID ASC);

CREATE UNIQUE INDEX PK_API_SELECTED_INDEX_9 ON API_SELECTED (API_TYPE_ID ASC);

CREATE UNIQUE INDEX PK_EXECUTIONPLAN_1_INDEX_2 ON EXECUTION_PLAN (CONFIGURATION_TEMPLATE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F ON API (API_ID ASC);

CREATE UNIQUE INDEX PK_CRUD_OPERATION_TYPE_0_INDEX_4 ON CRUD_OPERATION_TYPE (API_TYPE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FF ON EXECUTION_REPORT_DATA (EXECUTION_REPORT_DATA_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2 ON EXECUTION_PLAN (EXECUTION_PLAN_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON CRUD_OPERATION_TYPE (CRUD_OPERATION_TYPE_ID ASC);

CREATE UNIQUE INDEX PK_API_0_INDEX_F ON API (ACCOUNT_ID ASC);

CREATE UNIQUE INDEX PK_TEST_CONFIGURATION_INDEX_D ON TEST_CONFIGURATION (OBJECT_SIZE_REPORT_UNIT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON ACCOUNT (ACCOUNT_ID ASC);

CREATE UNIQUE INDEX PK_API_SELECTED_0_INDEX_9 ON API_SELECTED (TESTCONFIGURATION_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A ON EXECUTION_REPORT (EXECUTION_REPORT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D ON TEST_CONFIGURATION (TESTCONFIGURATION_ID ASC);

CREATE UNIQUE INDEX PK_EXECUTION_REPORT_DATA_INDEX_F ON EXECUTION_REPORT_DATA (EXECUTION_REPORT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_9 ON API_SELECTED (API_SELECTED_ID ASC);

CREATE UNIQUE INDEX PK_API_1_INDEX_F ON API (API_TYPE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6 ON API_TYPE (API_TYPE_ID ASC);

CREATE UNIQUE INDEX PK_EXECUTIONPLAN_0_INDEX_2 ON EXECUTION_PLAN (ACCOUNT_ID ASC);

CREATE UNIQUE INDEX PK_EXECUTIONPLAN_2_INDEX_2 ON EXECUTION_PLAN (TESTCONFIGURATION_ID ASC);

CREATE UNIQUE INDEX PK_EXECUTION_PLAN_INDEX_2 ON EXECUTION_PLAN (EXECUTION_REPORT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_AA ON OBJECT_SIZE_REPORT_UNIT (OBJECT_SIZE_REPORT_UNIT_ID ASC);

CREATE UNIQUE INDEX PK_CONFIGURATION_TEMPLATE_INDEX_1 ON CONFIGURATION_TEMPLATE (CONF_TEMP_OBJECT_SIZE_REPORT_UNIT_ID ASC);

CREATE UNIQUE INDEX PK_TEST_PLAN_OPERATION_1_INDEX_6 ON TEST_PLAN_OPERATION (CRUD_OPERATION_TYPE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON CONFIGURATION_TEMPLATE (CONFIGURATION_TEMPLATE_ID ASC);

ALTER TABLE CONFIGURATION_TEMPLATE ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (CONFIGURATION_TEMPLATE_ID);

ALTER TABLE TEST_CONFIGURATION ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY (TESTCONFIGURATION_ID);

ALTER TABLE CONFIGURATION_TEMPLATE ADD CONSTRAINT PK_CONFIGURATION_TEMPLATE_INDEX_1 UNIQUE (CONF_TEMP_OBJECT_SIZE_REPORT_UNIT_ID);

ALTER TABLE API ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY (API_ID);

ALTER TABLE CRUD_OPERATION_TYPE ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (CRUD_OPERATION_TYPE_ID);

ALTER TABLE EXECUTION_PLAN ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (EXECUTION_PLAN_ID);

ALTER TABLE EXECUTION_REPORT_DATA ADD CONSTRAINT CONSTRAINT_FF PRIMARY KEY (EXECUTION_REPORT_DATA_ID);

ALTER TABLE EXECUTION_REPORT ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (EXECUTION_REPORT_ID);

ALTER TABLE TEST_PLAN_OPERATION ADD CONSTRAINT CONSTRAINT_61 PRIMARY KEY (TEST_PLAN_OPERATION_ID);

ALTER TABLE CRUD_OPERATION_TYPE ADD CONSTRAINT PK_CRUD_OPERATION_TYPE_0_INDEX_4 UNIQUE (API_TYPE_ID);

ALTER TABLE OBJECT_SIZE_REPORT_UNIT ADD CONSTRAINT CONSTRAINT_AA PRIMARY KEY (OBJECT_SIZE_REPORT_UNIT_ID);

ALTER TABLE API_TYPE ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY (API_TYPE_ID);

ALTER TABLE ACCOUNT ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE API_SELECTED ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY (API_SELECTED_ID);

ALTER TABLE OBJECT_SIZE_REPORT_UNIT ADD CONSTRAINT FK_OBJECT_SIZE_REPORT_UNIT_CONFIGURATION_TEMPLATE FOREIGN KEY (OBJECT_SIZE_REPORT_UNIT_ID)
	REFERENCES CONFIGURATION_TEMPLATE (CONF_TEMP_OBJECT_SIZE_REPORT_UNIT_ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE API_TYPE ADD CONSTRAINT FK_API_TYPE_CRUD_OPERATION_TYPE FOREIGN KEY (API_TYPE_ID)
	REFERENCES CRUD_OPERATION_TYPE (API_TYPE_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

